### ISSUE TITLE
Deadlock in Client.Close

### ISSUE THREAD

**Issue by frekui** [Unleash/unleash-client-go#48]
Calling Client.Close leads to a deadlock due to a write to a nil channel in repository.go. With this diff
```
diff --git a/spec_test.go b/spec_test.go
index 9b47c90..f5354e5 100644
--- a/spec_test.go
+++ b/spec_test.go
@@ -70,6 +71,7 @@ func (td TestDefinition) Run(t *testing.T) {
                client, err := td.Mock()
                assert.NoError(t, err)
                t.Run(test.Description, test.RunWithClient(client))
+               client.Close()
                td.Unmock()
        }
 }
```
I get the backtrace
```
goroutine 20 [chan send (nil chan)]:
github.com/Unleash/unleash-client-go/v3.(*repository).Close(...)
	/home/frekui/code/unleash-client-go/repository.go:124
github.com/Unleash/unleash-client-go/v3.(*Client).Close(0xc0001412c0, 0xc00001c800, 0x1b)
	/home/frekui/code/unleash-client-go/client.go:264 +0x4a
github.com/Unleash/unleash-client-go/v3.TestDefinition.Run(0xc00001c7c0, 0x12, 0x1, 0xc0000cc540, 0x3, 0x4, 0xc000099440, 0x5, 0x6, 0xc0000e4900)
	/home/frekui/code/unleash-client-go/spec_test.go:74 +0x1be
testing.tRunner(0xc0000e4900, 0xc000138fa0)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
```
when running the tests. It seems the Client.closed channel isn't initialized either.

**Comment by frekui** [comment]
Fixed by #49, closing.
